<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once('vendor/autoload.php');
require_once('config/application.php');
require_once(ABSPATH . 'wp-settings.php');

define('WP_CACHE', true); //Added by WP-Cache Manager
if ( ! defined( 'SAVEQUERIES' ) ) {
  define( 'SAVEQUERIES', true );
}

define('WP_DEBUG', true); //Added by WP-Cache Manager

define( 'WP_MEMORY_LIMIT', '96MB' );